sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 123
  alioss:
    endpoint: oss-cn-nanjing.aliyuncs.com
    access-key-id: LTAI5tAJT2tekzRqsdKMh16C
    access-key-secret: FUmRtu8U6ivBI3aDL6hJSYXohLNS6J
    bucket-name: sky-take-out-jimmy